#!/usr/bin/env node
/**
 * Writes registry.json and src/app/glass.generated.css from registry/items.mjs
 * and registry/tokens.mjs. Both outputs are generated — edit the sources.
 */
import { writeFileSync } from "node:fs"
import { blocks, components, foundations, nativeItems } from "../registry/items.mjs"
import { glassCss, glassVars, palettes, paletteVars } from "../registry/tokens.mjs"

const dusk = paletteVars(palettes.dusk)
const auroraOnly = (vars) => Object.fromEntries(Object.entries(vars).filter(([k]) => k.startsWith("aurora-")))

// The foundation carries the glass tokens plus Dusk's aurora, so the aurora works before any theme is added.
const style = foundations.find((f) => f.name === "glass-style")
style.cssVars = {
  theme: glassVars.theme,
  light: { ...glassVars.light, ...auroraOnly(dusk.light) },
  dark: { ...glassVars.dark, ...auroraOnly(dusk.dark) },
}
style.css = glassCss

const themes = Object.entries(palettes).map(([key, p]) => ({
  name: `theme-${key}`,
  type: "registry:theme",
  title: `${p.title} theme`,
  description: `${p.description} Sets the accent, ring, aurora and chart colours for light and dark.`,
  categories: ["glass", "themes"],
  cssVars: paletteVars(p),
}))

const registry = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: "glasscn",
  homepage: "{REGISTRY_URL}",
  items: [...foundations, ...themes, ...components, ...blocks, ...nativeItems],
}
writeFileSync("registry.json", JSON.stringify(registry, null, 2) + "\n")

// ---- the docs site's CSS: exactly what ships, plus palette presets keyed by data-palette ----
const decl = (vars) => Object.entries(vars).map(([k, v]) => `  --${k}: ${v};`).join("\n")
const block = (selector, body, depth = 0) => {
  const pad = "  ".repeat(depth)
  const inner = Object.entries(body)
    .map(([k, v]) => (typeof v === "object" ? block(k, v, depth + 1) : `${pad}  ${k}: ${v};`))
    .join("\n")
  return `${pad}${selector} {\n${inner}\n${pad}}`
}

const css = [
  "/* Generated by scripts/generate.mjs from registry/tokens.mjs — do not edit. */",
  "",
  `@theme inline {\n${decl(glassVars.theme)}\n}`,
  "",
  `:root {\n${decl({ ...glassVars.light, ...dusk.light })}\n}`,
  "",
  `.dark {\n${decl({ ...glassVars.dark, ...dusk.dark })}\n}`,
  "",
  ...Object.entries(palettes).flatMap(([key, p]) => {
    const v = paletteVars(p)
    return [`:root[data-palette="${key}"] {\n${decl(v.light)}\n}`, `:root.dark[data-palette="${key}"] {\n${decl(v.dark)}\n}`, ""]
  }),
  `:root {\n${decl(Object.fromEntries(Object.entries(palettes).map(([k, p]) => [`swatch-${k}`, p.light.primary])))}\n}`,
  `.dark {\n${decl(Object.fromEntries(Object.entries(palettes).map(([k, p]) => [`swatch-${k}`, p.dark.primary])))}\n}`,
  "",
  ...Object.entries(glassCss).map(([k, v]) => block(k, v)),
  "",
].join("\n")
writeFileSync("src/app/glass.generated.css", css)

console.log(`registry.json: ${registry.items.length} items · glass.generated.css written`)

// ---- docs: every shipped file and every demo, highlighted once here (shiki dual themes) ----
const { readFileSync, existsSync } = await import("node:fs")
const { createHighlighter } = await import("shiki")
const highlighter = await createHighlighter({ themes: ["github-light", "github-dark"], langs: ["tsx", "ts", "css", "json", "bash"] })
const highlight = (code, lang = "tsx") => highlighter.codeToHtml(code, { lang, themes: { light: "github-light", dark: "github-dark" }, defaultColor: false })

const sources = {}
for (const item of registry.items) {
  if (!item.files?.length) continue
  sources[item.name] = item.files.map((f) => {
    const code = readFileSync(f.path, "utf8")
    return { path: f.target.replace(/^@(\w+)\//, (_, a) => `${a}/`), code, html: highlight(code, f.path.endsWith(".ts") ? "ts" : "tsx") }
  })
}
const demos = {}
for (const item of [...components, ...blocks]) {
  const path = `src/components/demos/${item.name}.tsx`
  if (!existsSync(path)) continue
  const code = readFileSync(path, "utf8")
  demos[item.name] = { code, html: highlight(code) }
}
const cssVarsCode = [
  ":root {",
  ...Object.entries({ ...glassVars.light, ...auroraOnly(dusk.light) }).map(([k, v]) => `  --${k}: ${v};`),
  "}",
  "",
  ".dark {",
  ...Object.entries({ ...glassVars.dark, ...auroraOnly(dusk.dark) }).map(([k, v]) => `  --${k}: ${v};`),
  "}",
].join("\n")
const snippets = { tokens: { code: cssVarsCode, html: highlight(cssVarsCode, "css") } }
writeFileSync(
  "src/lib/sources.generated.ts",
  `// Generated by scripts/generate.mjs — do not edit.\nexport interface Source { code: string; html: string }\nexport const sources: Record<string, (Source & { path: string })[]> = ${JSON.stringify(sources)}\nexport const demoSources: Record<string, Source> = ${JSON.stringify(demos)}\nexport const snippets: Record<string, Source> = ${JSON.stringify(snippets)}\n`
)
console.log(`sources.generated.ts: ${Object.keys(sources).length} items, ${Object.keys(demos).length} demos`)
