#!/usr/bin/env node
/**
 * Writes registry.json, src/app/glass.generated.css and src/lib/sources.generated.ts
 * from registry/items.mjs, registry/stylesheet.mjs and src/lib/glass-theme.ts (the
 * token schema and presets). All three outputs are generated — edit the sources.
 */
import { writeFileSync } from "node:fs"
import { blocks, components, foundations, nativeItems } from "../registry/items.mjs"
import { stylesheet, themeTokens } from "../registry/stylesheet.mjs"
import { DENSITIES, MATERIALS, MOTIONS, PALETTES, SHAPES, TOKENS, createGlassTheme, defaultTheme, themeToCss } from "../src/lib/glass-theme.ts"

const base = defaultTheme()
const groupOf = Object.fromEntries(TOKENS.map((t) => [t.name, t.group]))
const pickGroups = (tokens, groups, extra = []) => Object.fromEntries(Object.entries(tokens).filter(([k]) => groups.includes(groupOf[k]) || extra.includes(k)))
const notAccent = (tokens) => Object.fromEntries(Object.entries(tokens).filter(([k]) => !["primary", "primary-foreground", "ring"].includes(k) && !k.startsWith("chart-")))

// The foundation: every primitive except the accent and charts (those are the user's
// shadcn colours until they add a palette), including Dusk's aurora so it works alone.
const style = foundations.find((f) => f.name === "glass-style")
style.cssVars = { theme: themeTokens, light: notAccent(base.light), dark: notAccent(base.dark) }
style.css = stylesheet

// Preset items. Each carries the WHOLE of its groups, so adding one resets what a previous one set.
const presetItem = (name, title, description, theme, groups, extra = []) => ({
  name,
  type: "registry:theme",
  title,
  description,
  categories: ["glass", "themes"],
  cssVars: { light: pickGroups(theme.light, groups, extra), dark: pickGroups(theme.dark, groups, extra) },
})
const themes = [
  ...Object.entries(PALETTES).map(([k, p]) =>
    presetItem(`theme-${k}`, `${p.title} palette`, `${p.description} Sets the accent, ring, five chart colours, the aurora and the ground for light and dark.`, createGlassTheme({ palette: k }), ["Colour"])
  ),
  ...Object.entries(MATERIALS).map(([k, m]) =>
    presetItem(`material-${k}`, `${m.title} material`, `${m.description} Sets frost, blur, saturation, sheen, grain, rim and depth.`, createGlassTheme({ material: k }), ["Material", "Rim", "Depth"])
  ),
  ...Object.entries(SHAPES).map(([k, m]) => presetItem(`shape-${k}`, `${m.title} shape`, `${m.description} Sets every corner radius.`, createGlassTheme({ shape: k }), ["Shape"])),
  ...Object.entries(MOTIONS).map(([k, m]) =>
    presetItem(`motion-${k}`, `${m.title} motion`, `${m.description} Sets duration, easing, press and aurora speed.`, createGlassTheme({ motion: k }), ["Motion"], ["aurora-speed"])
  ),
  ...Object.entries(DENSITIES).map(([k]) =>
    presetItem(`density-${k}`, `${k[0].toUpperCase()}${k.slice(1)} density`, `Scales control heights, paddings and card spacing (×${DENSITIES[k]}).`, createGlassTheme({ density: k }), ["Density"])
  ),
]

const registry = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: "glasscn",
  homepage: "{REGISTRY_URL}",
  items: [...foundations, ...themes, ...components, ...blocks, ...nativeItems],
}
writeFileSync("registry.json", JSON.stringify(registry, null, 2) + "\n")

// ---- the docs site's CSS: what ships, the full default theme, and palette presets keyed by data-palette ----
const block = (selector, body, depth = 0) => {
  const pad = "  ".repeat(depth)
  const inner = Object.entries(body)
    .map(([k, v]) => (typeof v === "object" ? block(k, v, depth + 1) : `${pad}  ${k}: ${v};`))
    .join("\n")
  return `${pad}${selector} {\n${inner}\n${pad}}`
}
const decl = (vars) => Object.entries(vars).map(([k, v]) => `  --${k}: ${v};`).join("\n")
const css = [
  "/* Generated by scripts/generate.mjs — do not edit. */",
  "",
  `@theme inline {\n${decl(themeTokens)}\n}`,
  "",
  themeToCss(createGlassTheme()),
  "",
  ...Object.keys(PALETTES).map((k) => themeToCss(createGlassTheme({ palette: k }), { selector: `:root[data-palette="${k}"]`, darkSelector: `:root.dark[data-palette="${k}"]`, only: base })),
  "",
  `:root {\n${decl(Object.fromEntries(Object.entries(PALETTES).map(([k, p]) => [`swatch-${k}`, p.theme.light.primary])))}\n}`,
  `.dark {\n${decl(Object.fromEntries(Object.entries(PALETTES).map(([k, p]) => [`swatch-${k}`, p.theme.dark.primary])))}\n}`,
  "",
  ...Object.entries(stylesheet).map(([k, v]) => block(k, v)),
  "",
].join("\n")
writeFileSync("src/app/glass.generated.css", css)
console.log(`registry.json: ${registry.items.length} items (${themes.length} themes) · glass.generated.css written`)

// ---- docs: every shipped file and every demo, highlighted once here (shiki dual themes) ----
const { readFileSync, existsSync } = await import("node:fs")
const { createHighlighter } = await import("shiki")
const highlighter = await createHighlighter({ themes: ["github-light", "github-dark"], langs: ["tsx", "ts", "css", "json", "bash"] })
const highlight = (code, lang = "tsx") => highlighter.codeToHtml(code, { lang, themes: { light: "github-light", dark: "github-dark" }, defaultColor: false })

const sources = {}
for (const item of registry.items) {
  if (!item.files?.length) continue
  sources[item.name] = item.files.map((f) => {
    const code = readFileSync(f.path, "utf8")
    return { path: f.target.replace(/^@(\w+)\//, (_, a) => `${a}/`), code, html: highlight(code, f.path.endsWith(".ts") ? "ts" : "tsx") }
  })
}
const demos = {}
for (const item of [...components, ...blocks]) {
  const path = `src/components/demos/${item.name}.tsx`
  if (!existsSync(path)) continue
  const code = readFileSync(path, "utf8")
  demos[item.name] = { code, html: highlight(code) }
}
const cssVarsCode = themeToCss({ light: style.cssVars.light, dark: style.cssVars.dark })
const snippets = { tokens: { code: cssVarsCode, html: highlight(cssVarsCode, "css") } }
writeFileSync(
  "src/lib/sources.generated.ts",
  `// Generated by scripts/generate.mjs — do not edit.\nexport interface Source { code: string; html: string }\nexport const sources: Record<string, (Source & { path: string })[]> = ${JSON.stringify(sources)}\nexport const demoSources: Record<string, Source> = ${JSON.stringify(demos)}\nexport const snippets: Record<string, Source> = ${JSON.stringify(snippets)}\n`
)
console.log(`sources.generated.ts: ${Object.keys(sources).length} items, ${Object.keys(demos).length} demos`)
